"""add_password_hash_to_links

Revision ID: 1abfa4dcdaaf
Revises: 20260626_01_owner_id_to_links
Create Date: 2026-06-27 17:57:47.650481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abfa4dcdaaf'
down_revision = '20260626_01_owner_id_to_links'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_links_original_url'), table_name='links')
    op.create_index(op.f('ix_links_original_url'), 'links', ['original_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_original_url'), table_name='links')
    op.create_index(op.f('ix_links_original_url'), 'links', ['original_url'], unique=True)
    op.drop_column('links', 'password_hash')
    # ### end Alembic commands ###
